# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='user',
            new_name='users',
        ),
    ]
